name: Update README with Latest Medium Post

on:
  schedule:
    - cron: '0 * * * *' # Her saat başı çalıştır
  workflow_dispatch: # Manuel çalıştırma seçeneği

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils

      - name: Fetch latest Medium post
        id: fetch-medium
        run: |
          FEED_URL="https://medium.com/feed/@marufakan"
          curl -s $FEED_URL | xmllint --format - > medium_feed.xml
          TITLE=$(xmllint --xpath "string(//item[1]/title)" medium_feed.xml)
          LINK=$(xmllint --xpath "string(//item[1]/link)" medium_feed.xml)
          DESCRIPTION=$(xmllint --xpath "string(//item[1]/description)" medium_feed.xml | sed 's/<[^>]*>//g' | head -c 200)
          IMAGE_URL=$(curl -s $LINK | grep -oP '(?<=<img src=").*?(?=")' | head -n 1 || echo "https://cdn-icons-png.flaticon.com/512/2111/2111505.png")
          echo "::set-output name=title::$TITLE"
          echo "::set-output name=link::$LINK"
          echo "::set-output name=description::$DESCRIPTION"
          echo "::set-output name=image_url::$IMAGE_URL"

      - name: Update README
        run: |
          TITLE="${{ steps.fetch-medium.outputs.title }}"
          LINK="${{ steps.fetch-medium.outputs.link }}"
          DESCRIPTION="${{ steps.fetch-medium.outputs.description }}"
          IMAGE_URL="${{ steps.fetch-medium.outputs.image_url }}"
          echo "Updating README.md with the latest Medium post..."
          sed -i "/<!-- BLOG-POST-LIST:START -->/,/<!-- BLOG-POST-LIST:END -->/c\<!-- BLOG-POST-LIST:START -->\n<p align='left'>\n  <img src='${IMAGE_URL}' alt='${TITLE}' width='400'/>\n  <br />\n  <strong><a href='${LINK}' target='_blank'>${TITLE}</a></strong>\n  <br />\n  <em>${DESCRIPTION}...</em>\n</p>\n<!-- BLOG-POST-LIST:END -->" README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update latest Medium article" || echo "No changes detected"
          git push
